### PR TITLE
Add recipe for 'browsh' Modern text-based browser for console/TTY.

### PR DESCRIPTION
**Pull request by TimothyDJones**

### CODE REVIEW

**Comment by candrewlee14** [comment]
Thank you!
Would you mind rebasing onto main?
A new PR changed the schema and moved bin_path into each of OS sections, so you may need a small change there.

**Comment by jolheiser** [comment]
As well, `macos` is supported.  Just need to add an ignore for `arm64` and give `os_map.macos.ext = tar.gz`

**Comment by candrewlee14** [comment]
@jolheiser Related idea:

I've been thinking maybe we could put functionality to test that ignored binaries for OS/arch combinations actually aren't distributed.
It'd probably be behind a flag in bintest like --try-ignored.

**Comment by jolheiser** [comment]
> @jolheiser Related idea:
> 
> I've been thinking maybe we could add functionality to test that ignored binaries for OS/arch combinations actually aren't distributed. It'd probably be behind a flag in bintest like --try-ignored.

I think the trick there is that, for this case as an example, I don't know of a good way to programmatically figure it out. 
https://github.com/browsh-org/browsh/releases/tag/v1.6.4
macOS seems to be the _only_ one with `tar.gz`, so it's sort of an edge case among its own downloads.

-----

On another note, currently only amd64 and arm64 are tested regardless, even if the recipe specifies `386` or `arm`.
imo this is almost worth adding more (perhaps behind a flag), because while a missing arch is a recipe bug, an incorrect recipe is a runtime bug

**Comment by jolheiser** [comment]
> > As well, `macos` is supported.  Just need to add an ignore for `arm64` and give `os_map.macos.ext = tar.gz`
> 
> Does the global is_binary not cause a problem with the tar.gz? Do we need to move is_binary to be a OS setting as well?

Hmm, it should. `bintest` passes (so I naively thought it should work), but without unpacking I suspect that there would be an issue at runtime.

**Comment by candrewlee14** [comment]
Hmm, seems like we may need to clarify the field name to `is_raw_binary` or something in that case as well. Yeah, inconvenient to change all the files. Hopefully there won't be too many more of these widespread changes but this one is for the best.

**Comment by candrewlee14** [comment]
The blocking changes are now merged, so this can be fixed now.

**Pull request closed without merging**
