### PR TITLE
Add gh

### PR DESCRIPTION
**Pull request by jolheiser**
https://github.com/cli/cli

### CODE REVIEW

**Comment by jolheiser** [comment]
I'm not entirely sure why this is failing...
Understandably it's awkward because Windows releases don't have the root folder, but locally my workaround seems to work fine on both Windows and WSL.

**Comment by jolheiser** [comment]
Perhaps each item in `os_map` could specify `has_root` (defaulting to `extract_has_root`)?

**Comment by candrewlee14** [comment]
Yeah, I've wondered about making that a OS-specific setting before. What do you think? Leave the global setting and have overrides, or move the setting to only be OS specific?

What about an `overrides` field that maps to the OSs which can override root recipe settings?

**Comment by jolheiser** [comment]
> Leave the global setting and have overrides

This was my initial thought, and it would be sort of nice to not have to change all the recipes at once.

> move the setting to only be OS specific

On the other hand, I like that this is explicit.

> What about an overrides field that maps to the OSs which can override root recipe settings?

I like this in theory for flexibility, but it seems like it could add complexity (too much?) to both the code and recipes.

**Comment by candrewlee14** [comment]
Have you moved the bin_paths into the OSs here yet?

**Comment by jolheiser** [comment]
> Have you moved the bin_paths into the OSs here yet?

Did it now.

**Comment by candrewlee14** [comment]
Legendary, looks like the tests pass. Gh is a tool I install on all my dev boxes, so great work adding it in, that's gonna make it a lot easier to manage.

**Pull request merged**
