### PR TITLE
Add usql

### PR DESCRIPTION
**Pull request by jolheiser**
This PR adds [usql](https://github.com/xo/usql).

### CODE REVIEW

**Comment by candrewlee14** [comment]
Mapping `arch_map` explicitly to its corresponding arch string in the binary name is required, even if it's the same string.
If `amd64: amd64` was not on there, there would no supported architectures. That's the key: the values that are mapped in `arch_map` are the supported architectures. The default if no `arch_map` is nothing, which means no architectures are supported...which doesn't make much sense to have a package for.

**Comment by jolheiser** [comment]
> Mapping `arch_map` explicitly to its corresponding arch string in the binary name is required, even if it's the same string. If `amd64: amd64` was not on there, there would no supported architectures. That's the key: the values that are mapped in `arch_map` are the supported architectures. The default if no `arch_map` is nothing, which means no architectures are supported...which doesn't make much sense to have a package for.

Aha! Okay, that makes sense. My bad, thanks for the patience.

**Comment by candrewlee14** [comment]
No worries! The other part this PR needs is a sister PR in the webman repo to support `.bz2` decompression.
Try running `webman dev bintest usql -l [WEBMAN-PKGS-DIR]` and you'll see it doesn't have that yet.

**Comment by jolheiser** [comment]
> No worries! The other part this PR needs is a sister PR in the webman repo to support `.bz2` decompression. Try running `webman dev bintest usql -l [WEBMAN-PKGS-DIR]` and you'll see it doesn't have that yet.

I just came back here to mention this 😅 
Worked fine on Windows, ran on WSL and got that error. 
Will do!

**Comment by candrewlee14** [comment]
Thanks!
I'm not great at Github actions, but if you want to write a PR that somehow runs `bintest` on only the changed packages, that would be a super helpful status check.

**Comment by candrewlee14** [comment]
With the new status check merged #11, try pushing a new empty commit to retrigger the checks and let's see how it looks.

**Pull request merged**
